---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.23.6-bullseye

inputs:
  - name: dp-cookies
    path: dp-cookies

run:
  path: dp-cookies/ci/scripts/build.sh
